plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.shl'
version = '0.0.1-SNAPSHOT'
description = 'train-reservations-jmeter-test'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // common & for step1
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.projectlombok:lombok:1.18.30'
//    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    runtimeOnly 'org.postgresql:postgresql'

    // for step2
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    
    // for step3: Redis Connection Pool ex) spring data redis에서 lettuce or jedis 커넥션 풀 관리시 사용!
    implementation 'org.apache.commons:commons-pool2:2.12.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
