version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: reservation_db_container
    environment:
      POSTGRES_DB: train_reservations_jmeter_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trainreservationsjemetertest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: reservation_redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # 컨테이너 시작 시 실행할 명령어
    # --appendonly yes : AOF(Append Only File) 모드 활성화, 데이터 지속성 유지
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: reservation_rabbitmq_container
    ports:
      - "5672:5672"   # AMQP 포트
      - "15672:15672" # Management UI 포트
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: reservation_kafka_container
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: reservation_zookeeper_container
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  kafka_data:
  zookeeper_data:
