version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: reservation_db_container
    environment:
      POSTGRES_DB: train_reservations_jmeter_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trainreservationsjemetertest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
