version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: reservation_db_container
    environment:
      POSTGRES_DB: train_reservations_jmeter_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trainreservationsjemetertest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: reservation_redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes # 컨테이너 시작 시 실행할 명령어
    # --appendonly yes : AOF(Append Only File) 모드 활성화, 데이터 지속성 유지
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
